name: Deploy

on: 
  push:
    branches:
      - master
      - feature/*

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@master

    - name: 'Publish'
      uses: azure/webapps-deploy@v1
      with: 
        app-name: blockcore
        publish-profile: ${{ secrets.azureWebAppPublishProfile }}
        package: ./